Naztec.Web/Controllers/DashboardController.cs
namespace Naztec.Web.Controllers
{
    using System.Web.Mvc;
    using Naztec.Web.Infrastructure.Contracts;
    using Naztec.Web.Infrastructure.Attributes;
    using Naztec.Web.ViewModels;

    [GlobalAuthorize]
    public class DashboardController : BaseController
    {
        public DashboardController(IApplicationStore applicationStore, ISessionStore sessionStore)
            :base(applicationStore,sessionStore)
        {
            
        }

        public ActionResult Index()
        {
            DashboardVM viewModel = new DashboardVM();

            return View(viewModel);
        }
    }
}

Naztec.Web/Controllers/ImageController.cs
namespace Naztec.Web.Controllers
{
    using Domain.Contracts;
    using Domain.Entities;
    using Infrastructure.Attributes;
    using Infrastructure.Contracts;
    using log4net;
    using System;
    using System.IO;
    using System.Web.Mvc;
    using System.Web.UI;
    using ViewModels;

    [NoAuthorize]
    public class ImageController : BaseController
    {
        private static readonly ILog Log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private IProfileService profileService;

        public ImageController(IApplicationStore applicationStore, ISessionStore sessionStore, IProfileService profileService)
            : base(applicationStore, sessionStore)
        {
            this.profileService = profileService;
        }

        public ImageController(IApplicationStore applicationStore, ISessionStore sessionStore)
           : base(applicationStore, sessionStore)
        {
            
        }

        [OutputCache(Duration = int.MaxValue, Location = OutputCacheLocation.Client, VaryByParam = "*")]
        [Route("Image/Picture/{imageId}")]
        public ActionResult Picture(string imageId)
        {
            BaseVM viewModel = new BaseVM(this.ApplicationStore, this.SessionStore);

            var memberImagePath = Path.Combine(Server.MapPath("~/Images/profile/"), $"{imageId}.jpg");

            Guid validImageGuid;

            bool isValidGuid = Guid.TryParse(imageId, out validImageGuid);

            if (isValidGuid && validImageGuid != Guid.Empty)
            {
                if (System.IO.File.Exists(memberImagePath))
                {
                    return this.File(memberImagePath, "image/jpeg");
                }
                else
                {
                    var imageEntity = this.profileService.GetProfileImageByImageName(validImageGuid);

                    var result = this.CreateProfileImageInPath(validImageGuid, imageEntity.ProfileImage);

                    if (result)
                    {
                        return this.File(memberImagePath, "image/jpeg");
                    }
                }
            }

            var defaultImagePath = Server.MapPath("~/Images/profile/noimage.jpg");

            return this.File(defaultImagePath, "image/jpeg");
        }

        [OutputCache(Duration = int.MaxValue, Location = OutputCacheLocation.Client, VaryByParam = "*")]
        [Route("Image/Company/{imageId}")]
        public ActionResult Company(string imageId)
        {
            BaseVM viewModel = new BaseVM(this.ApplicationStore, this.SessionStore);

            var companyImagePath = Path.Combine(Server.MapPath("~/Images/company/"), $"{imageId}.jpg");

            Guid validImageGuid;

            bool isValidGuid = Guid.TryParse(imageId, out validImageGuid);

            if (isValidGuid && validImageGuid != Guid.Empty)
            {
                //if (System.IO.File.Exists(companyImagePath))
                //{
                //    return this.File(companyImagePath, "image/jpeg");
                //}
                //else
                //{
                //    var companyimageEntity = this.profileService.GetProfileImageByImageName(validImageGuid);

                //    var result = this.CreateCompanyImageInPath(validImageGuid, imageEntity.ProfileImage);

                //    if (result)
                //    {
                //        return this.File(companyImagePath, "image/jpeg");
                //    }
                //}
            }

            var defaultCompanyImagePath = Server.MapPath("~/Images/company/nocompanylogo.jpg");

            return this.File(defaultCompanyImagePath, "image/jpeg");
        }

        public bool CreateProfileImageInPath(Guid? imageName, byte[] profileImage)
        {
            try
            {
                string filePath = Server.MapPath(NaztecConstants.ProfileImage.ServerImagePath + Path.GetFileName(imageName.ToString() + ".jpg"));

                System.IO.File.WriteAllBytes(filePath, profileImage);

                return true;
            }
            catch (Exception ex)
            {
                Log.Error(ex.Message, ex);

                return false;
            }
        }
    }
}

Naztec.Web/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Naztec.Web.Infrastructure.Contracts;
using Naztec.Web.ViewModels.Notifications;

namespace Naztec.Web.Controllers
{
    public class NotificationsController : BaseController
    {
        public NotificationsController(IApplicationStore applicationStore, ISessionStore sessionStore) : base(applicationStore, sessionStore)
        {
        }

        public ActionResult Index()
        {
            NotificationsVM viewModel = new NotificationsVM(this.ApplicationStore, this.SessionStore);

            return View(viewModel);
        }
    }
}

Naztec.Web/Controllers/ProfileController.cs
using AutoMapper;
using Naztec.Domain.Contracts;
using Naztec.Domain.Entities;
using Naztec.Web.Infrastructure.Contracts;
using Naztec.Web.Infrastructure.Extensions;
using Naztec.Web.Models;
using Naztec.Web.ViewModels;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Naztec.Web.Controllers
{
    public class ProfileController : BaseController
    {
        private IProfileService profileService;
        private IAuthService authService;
        private IAuthenticationManager authenticationManager;

        public ProfileController(IAuthenticationManager authenticationManager, IApplicationStore applicationStore, ISessionStore sessionStore, IProfileService profileService, IAuthService authService)
            : base(applicationStore, sessionStore)
        {
            this.profileService = profileService;
            this.authenticationManager = authenticationManager;
            this.authService = authService;
        }

        public ActionResult Index()
        {
            return RedirectToAction("Manage");
        }

        public ActionResult Manage()
        {
            ProfileVM viewModel = new ProfileVM(this.ApplicationStore, this.SessionStore);

            viewModel.Profile = Mapper.Map<ProfileDM>(this.profileService.GetProfile(viewModel.UserName));
            viewModel.ChangePassword = new ChangePasswordDM();

            if (viewModel.Profile.ImageId != null)
            {
                string profilePath = NaztecConstants.ProfileImage.JsImagePath + viewModel.Profile.ImageId + ".jpg";

                string searchprofilePath = Server.MapPath(NaztecConstants.ProfileImage.ServerImagePath + viewModel.Profile.ImageId + ".jpg");

                viewModel.Profile.ProfileImageUrl = profilePath;

                if (!System.IO.File.Exists(searchprofilePath))
                {
                    var response = this.CreateImageInPath(viewModel.Profile.ImageId, viewModel.Profile.ProfileImage, NaztecConstants.ProfileImage.ServerImagePath);

                    if (!response)
                    {
                        viewModel.Profile.ProfileImageUrl = NaztecConstants.ProfileImage.JsImagePath + NaztecConstants.ProfileImage.DefaultImage;
                    }
                }
            }
            else
            {
                viewModel.Profile.ProfileImageUrl = NaztecConstants.ProfileImage.JsImagePath + NaztecConstants.ProfileImage.DefaultImage;
            }

            return View(viewModel);
        }

        [HttpPost]
        [Route("Profile/SaveProfile")]
        public ActionResult SaveProfile(ProfileDM profile)
        {
            var viewModel = new BaseVM(this.ApplicationStore, this.SessionStore);

            profile.Email = viewModel.UserName;

            if (profile.ImageId == null)
            {
                profile.ImageId = Guid.Empty;
            }

            if (!ModelState.IsValid)
            {
                return this.Json(new { success = false, message = ModelState.ToResponse().GetHtmlMessage() });
            }
            var response = this.profileService.SaveProfile(Mapper.Map<UserProfile>(profile));

            if (response.IsOk)
            {
                this.SessionStore.Set<string>(SessionConstants.FullName, profile.FirstName + " " + profile.LastName);
            }
            return this.Json(new { success = response.IsOk, message = response.GetHtmlMessage() });
        }

        [HttpPost]
        public async Task<ActionResult> SaveTheme(string theme)
        {
            var viewModel = new BaseVM(this.ApplicationStore, this.SessionStore);

            var response = await this.authService.WriteToUserClaims(viewModel.SessionSecurityUserId, NaztecConstants.Claims.SkinTheme, theme);

            var authenticationProperties = new AuthenticationProperties { };
            this.authenticationManager.SignIn(authenticationProperties, response.UserClaims);

            return this.Json(new { success = response.IsOk, message = response.GetHtmlMessage() });
        }

        public ActionResult AddProfileImage(string imageString)
        {
            if (imageString == null)
            {
                return this.Json(new { success = false, message = "Adding Image Failed" });
            }

            var viewModel = new ProfileImageVM(this.ApplicationStore, this.SessionStore);

            viewModel.ImageName = Guid.NewGuid();

            viewModel.ImageBinaryData = this.profileService.GetImageinByteArray(imageString);

            if (viewModel.ImageBinaryData != null)
            {
                viewModel.AppUserId = viewModel.SessionSecurityUserId;

                var response = this.profileService.AddImages(Mapper.Map<ProfileImageItem>(viewModel));

                Guid? profilePicture = null;

                if (response.IsOk)
                {
                    var creationResult = this.CreateImageInPath(viewModel.ImageName, viewModel.ImageBinaryData, NaztecConstants.ProfileImage.ServerImagePath);

                    if (creationResult)
                    {
                        this.SessionStore.Set(SessionConstants.AppUserImageId, viewModel.ImageName);

                        var deletionResult = this.DeleteImageInPath(response.Item.PreviousImageName, NaztecConstants.ProfileImage.ServerImagePath);

                        profilePicture = response.Item.ImageName;
                    }
                    else
                    {
                        profilePicture = response.Item.PreviousImageName;
                    }
                }

                return this.Json(new { success = response.IsOk, imageUrl = NaztecConstants.ProfileImage.JsImagePath + Path.GetFileName(profilePicture + ".jpg"), message = response.GetHtmlMessage() });
            }

            return this.Json(new { success = false, message = "No file Added" });
        }
    }
}

Naztec.Web/Views/Shared/_Aside.cshtml
@model Naztec.Web.ViewModels.BaseVM



@helper RenderMenu(IEnumerable<Naztec.Domain.Entities.AppMenuDTO> menuItems)
{
    foreach (var item in menuItems)
    {
        var rootClass = string.Empty;

        var childItems = Model.GetUserMenuByParentId(item.Id);

        if (childItems.Any())
        {
            <li class="treeview @(item.IsActiveParent ? "active menu-open" : string.Empty)">
                <a href="#">
                    <i class="@(item.ParentMenuId != null ? "fa fa-circle-o" : item.Class)"></i>
                    <span>@item.Text</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu" style="display: @(item.IsActiveParent ? "block" : "none");">
                    @RenderMenu(childItems)
                </ul>                    
            </li>
        }
        else
        {
            <li class="@(item.IsSelected ? "active" : string.Empty)">
                <a href="@item.Slug">
                    <i class="@(item.ParentMenuId != null ? "fa fa-circle-o" : item.Class)"></i>
                    <span>@item.Text</span>
                </a>
            </li>
        }
    }
}

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@Url.Action("Picture", "Image", new {area = "", imageId =  @Model.AppUserImageId != null ? Model.AppUserImageId.ToString() : "no-image" })" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@Model.SessionFullName</p>
                @*<a href="#"><i class="fa fa-circle text-success"></i> Online</a>*@
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            @RenderMenu(Model.GetUserMenuByParentId(null))
        </ul>

    </section>
    <!-- /.sidebar -->
</aside>

Naztec.Web/Views/Shared/_ControlSideBar.cshtml
 <!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
 immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

Naztec.Web/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2019 <a href="https://www.naztecgroup.com/">NAZTEC International Group</a>.</strong> All rights reserved.
</footer>

Naztec.Web/Views/Shared/_Header.cshtml
@model Naztec.Web.ViewModels.BaseVM

<header class="main-header">

    <!-- Logo -->
    <a href="@Url.Action("Index", "Dashboard", new { Area = "" })" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>NT</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Naztec</b></span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">               
                <!-- Notifications: style can be found in dropdown.less -->
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">0</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 0 notifications</li>
                        @*<li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                                        page and may cause design problems
                                    </a>
                                </li>                              
                            </ul>
                        </li>*@
                        <li class="footer"><a href="@Url.Action("Index", "Notifications", new { Area = "" })">View all</a></li>
                    </ul>
                </li>
               
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="@Url.Action("Picture", "Image", new {area = "", imageId = @Model.AppUserImageId != null ? Model.AppUserImageId.ToString() : "no-image" })" class="user-image" alt="User Image">
                        <span class="hidden-xs">@Model.SessionFullName</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="@Url.Action("Picture", "Image", new {area = "", imageId =  @Model.AppUserImageId != null ? Model.AppUserImageId.ToString() : "no-image" })" class="img-circle" alt="User Image">

                            <p>
                            @Model.SessionFullName
                                @*<small>Member since Nov. 2012</small>*@
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="@Url.Action("Manage","Profile", new { Area = "" })" class="btn btn-default btn-flat text-blue"><i class="fa fa-user"></i>&nbsp;Profile</a>
                               
                            </div>
                            <div class="pull-right">
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat text-red">
                                    <i class="fa fa-sign-out"></i>&nbsp;Sign out
                                </a>
                                @using (Html.BeginForm("LogOff", "Auth", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "" }))
                                {
                                    @Html.AntiForgeryToken()
                                }
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

    </nav>

</header>

Naztec.Web/Views/Shared/_PublicLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naztec</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/iCheck")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">   

    @RenderBody()    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/iCheck")

    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>

Naztec.Web/Views/Shared/_SecureLayout.cshtml
@model Naztec.Web.ViewModels.BaseVM

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naztec - @ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @Styles.Render("~/Content/css")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

</head>
<body class="hold-transition fixed sidebar-mini @Model.GetTheme()">
    <div class="wrapper">

        @{ Html.RenderPartial("_Header"); }

        @{ Html.RenderPartialIf("_Aside", Model, Request.IsAuthenticated); }
                
        <div class="content-wrapper">
            
            @RenderSection("PageHeader", false)
            
            <section class="content">

                @RenderBody()

            </section>
        </div>

        @{ Html.RenderPartial("_Footer");  }
    
       @{ Html.RenderPartial("_ControlSideBar");  }

    </div>

    <script src="~/Scripts/pages/dashboard.js"></script>

    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/bundles/charts")


    <script type="text/javascript">       
        naztec.init('@Url.Content("~/")');
        naztec.initSecured();
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>